presence1/config/routes.rb
Presence1::Application.routes.draw do
  resources :rooms, only: [:show] do
    resource :user
  end

end

presence1/app/models/room.rb
class Room < ActiveRecord::Base
  has_many :users, inverse_of: :room
end

presence1/app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :room, inverse_of: :users

  validate :room, presence: true
end

presence1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

presence1/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
    @room = Room.includes(:users).find_by(name: params[:id])
    begin
      @user = User.find(session[:current_user_id])
    rescue ActiveRecord::RecordNotFound
      @user = nil
    end

    respond_to do |format|
      if @user.nil?
        format.html { redirect_to new_room_user_path(@room.name) }
        format.json { render status: :unprocessable_entity }
      else
        format.html { render }
        # FIXME the json logic should probably be moved to a template
        format.json {
          # Remove the picture if it has not changed
          unless params[:newer_than].blank?
            @room.users.each do |u|
              u.last_pic = '' if u.updated_at.to_i <= params[:newer_than].to_i
            end
          end
          result = @room.as_json(include: :users)
          result['timestamp'] = @room.users.map {|u| u.updated_at }.max.to_i
          render json: result
        }
      end
    end
  end
end

presence1/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :set_room

  def new
    @user = @room.users.build
  end

  def create
    @user = @room.users.create(user_params)
    session[:current_user_id] = @user.id
    redirect_to room_path(@room.name)
  end

  def update
    @user = User.find(session[:current_user_id])
    respond_to do |format|
      if @user.update(user_params)
        format.json { head :no_content }
      else
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  protected

  def set_room
    @room = Room.find_by(name: params[:room_id])
  end

  def user_params
    params.require(:user).permit(:name, :last_pic, :pic_height)
  end
end

presence1/app/helpers/application_helper.rb
module ApplicationHelper
end

presence1/app/helpers/rooms_helper.rb
module RoomsHelper
end

presence1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Presence1</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

presence1/app/views/rooms/show.html.haml
%h2 Pics
#pics

#pics_local
  %canvas#pic{style: "display:none", data: {"user-id" => @user.id}}
  =image_tag "user_placeholder.png", id: "user-placeholder"
  %video#pic-video{style: "display:none"}
  %button#start Start sending pics
  %button#stop{style: "display:none"} Stop sending pics

%h2 Videos
#videos

#videos_local
  =image_tag "video_placeholder.png", id: "video-placeholder"
  %video#video{style: "display:none"}
  %button#join Start videocall
  %button#leave{style: "display:none"} Stop videocall

:javascript
  var janusRoom = 1234
  $(document).ready(function() {
    window.init_video();
    window.initJanus();
    $('#start').click(function () { window.startSending(20000) });
    $('#stop').click(window.stopSending);
    $('#join').click(function () { window.startVideo("http://192.168.0.108:8088/janus", "#{@user.name}") });
    $('#leave').click(window.stopVideo);

    window.getPics(5000);
  });

presence1/app/views/users/new.html.haml
%h1= "Join #{@room.name}"

=form_for [@room, @user], url: room_user_path(@room.name) do |f|
  = f.label "Name"
  = f.text_field :name
  = f.submit